### PR TITLE
Improvements of DisjunctiveIntervalMap & BasicRDMap

### PR DESCRIPTION
**Pull request by tomsik68**
Hi, I've been trying to integrate the DisjunctiveIntervalMap with semi-sparse RDA and encountered some issues along the way, so I decided to patch some of them myself. 

The following issues are fixed in this PR:
- missing includes
- it is impossible to iterate through `BasicRDMap` for some reason (`llvm-rd-dump` doesn't work either)
- behavior of `overlapsFull` when called on an empty map

There is still one more issue I don't really know how to fix, so I add a failing unit test at least. Briefly, when you add an interval `0-4` and then gradually add intervals `0-1`, `1-2`, `2-3` and `3-4`, the test terminates with the following message: `disjunctive-intervals-map-test: /home/xjasek/formela/dg/include/dg/analysis/ReachingDefinitions/DisjunctiveIntervalMap.h:335: void dg::analysis::rd::DisjunctiveIntervalMap<ValueT, IntervalValueT>::_check() const [with ValueT = int; IntervalValueT = int]: Assertion 'last.end < it->first.start' failed.`

Also, I used `rdmap-refactor` branch because I need `overlapsFull` method.

### CODE REVIEW

**Comment by mchalupa** [comment]
Great, thanks!

However, I'm getting this error:

```
In file included from /var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp:2:0:
/var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____42()’:
/var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp:424:6: error: converting to ‘std::tuple<int, int, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int, int, int}; <template-parameter-2-2> = void; _Elements = {int, int, int}]’
     }));
      ^
/var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp:424:6: error: converting to ‘std::tuple<int, int, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int, int, int}; <template-parameter-2-2> = void; _Elements = {int, int, int}]’
/var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp:424:6: error: converting to ‘std::tuple<int, int, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int, int, int}; <template-parameter-2-2> = void; _Elements = {int, int, int}]’
/var/xchalup4/dg/tests/disjunctive-intervals-map-test.cpp:424:6: error: converting to ‘std::tuple<int, int, int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {int, int, int}; <template-parameter-2-2> = void; _Elements = {int, int, int}]’
tests/CMakeFiles/disjunctive-intervals-map-test.dir/build.make:62: recipe for target 'tests/CMakeFiles/disjunctive-intervals-map-test.dir/disjunctive-intervals-map-test.cpp.o' failed
```

**Comment by mchalupa** [comment]
Otherwise it looks good.

**Comment by mchalupa** [comment]
The SIGSEGV mentioned in the last commit should be fixed by 78fb22e1c55d906b5a7b.

**Comment by mchalupa** [comment]
Rebased on master: https://github.com/mchalupa/dg/tree/rdmap-improv

**Comment by tomsik68** [comment]
In that case, I think we can close this.

**Pull request closed without merging**
