### PR TITLE
Fixed type in lib/CMakeLists.txt

### PR DESCRIPTION
**Pull request by jcarlson23**
Simple typo fix in lib rules

### CODE REVIEW

**Comment by mchalupa** [comment]
Hi,

That is not a typo. DG contains two libraries: `dgllvmdg` and `dgllvmsdg`. Did you have any problems with linking to `dgllvmdg`?

**Comment by jcarlson23** [comment]
I got a build error: 

CMake Error at lib/CMakeLists.txt:182 (set_target_properties):
  set_target_properties Can not find target to add properties to: dgllvmsdg

Seems like a typo...

**Comment by mchalupa** [comment]
Did the patch in this branch fix your problem?

https://github.com/mchalupa/dg/tree/cmake-macos-fix

**Comment by jcarlson23** [comment]
yeah, that works!  Thanks!

**Comment by mchalupa** [comment]
Great! I'll push that to master then.

**Pull request closed without merging**
