### PR TITLE
VR: extend to verify some cstr benchmarks

### PR DESCRIPTION
**Pull request by GiraffeReversed**
Tested on SV-COMP21_valid-memsafety category, changed no answers except for newly verified benchmarks.

Depends on VR: use fixed and refactored version #403

### CODE REVIEW

**Comment by GiraffeReversed** [comment]
I found some problem with this, so no need to look at this yet.

**Comment by mchalupa** [comment]
> I found some problem with this, so no need to look at this yet.

Is this PR now ready or you will do some more changes?

**Comment by mchalupa** [comment]
Hmm, I see there are some conflicts. I do not realize where they come from (but probably I did them, sorry). Could you, please, rebase?

**Comment by GiraffeReversed** [comment]
I will do the rebase, although I may get to it in the second half of December at the earliest (sorry :/). I may add more commits fixing some rather unlikely bugs.

**Comment by mchalupa** [comment]
Do you think you will be able to do the rebase in the near future?

**Comment by mchalupa** [comment]
ping

**Comment by GiraffeReversed** [comment]
Sorry! I'll try to look into it during this week.

**Comment by GiraffeReversed** [comment]
The code seems to be rebased all right :)

**Comment by mchalupa** [comment]
Thanks for this work.

**Pull request merged**
